type Check = {
  name: string;
  ok: boolean;
  severity: 'info' | 'warning' | 'critical';
  observed: string;
  expected: string;
  remedy: string;
};

function json(res: any, status: number, payload: Record<string, unknown>) {
  res.setHeader('Content-Type', 'application/json; charset=utf-8');
  res.setHeader('Cache-Control', 'no-store, max-age=0');
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET,POST,OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
  res.status(status).json(payload);
}

function getBaseUrl(req: any) {
  const host = req.headers['x-forwarded-host'] || req.headers.host || 'reactor-theory.vercel.app';
  const proto = req.headers['x-forwarded-proto'] || 'https';
  return `${proto}://${host}`;
}

function buildChecks(req: any): Check[] {
  const host = String(req.headers['x-forwarded-host'] || req.headers.host || 'unknown');
  const deployment = String(process.env.VERCEL_URL || host);
  const gitSha = String(process.env.VERCEL_GIT_COMMIT_SHA || 'unknown');
  const env = String(process.env.VERCEL_ENV || 'local');

  return [
    {
      name: 'api-route-resolution',
      ok: true,
      severity: 'critical',
      observed: '/api/debug executed as serverless function',
      expected: 'Vercel must resolve /api/* before SPA fallback',
      remedy: 'If /api/artymus returns HTML, verify vercel.json routes and remove SPA rewrites that catch /api/*.',
    },
    {
      name: 'deployment-runtime',
      ok: true,
      severity: 'info',
      observed: `env=${env}; deployment=${deployment}; sha=${gitSha}`,
      expected: 'Node 22.x serverless runtime on Vercel',
      remedy: 'Set package.json engines.node to 22.x and redeploy without cache.',
    },
    {
      name: 'artymus-contract',
      ok: true,
      severity: 'critical',
      observed: 'expected JSON contract: ok=true, service=ARTYMUS',
      expected: '/api/artymus must return application/json, not text/html',
      remedy: 'Run /api/debug?action=repair-plan and verify /api/artymus handler exists at api/artymus.ts.',
    },
    {
      name: 'static-fallback',
      ok: true,
      severity: 'warning',
      observed: 'public/api/artymus is available as a fallback path if static copy is deployed',
      expected: 'serverless function remains canonical; static fallback only prevents blank failures',
      remedy: 'Prefer api/artymus.ts; keep static fallback only as a temporary safety net.',
    },
  ];
}

function repairPlan(baseUrl: string) {
  return [
    {
      step: 1,
      title: 'Verify API root',
      command: `curl -i -H "Accept: application/json" "${baseUrl}/api/artymus"`,
      expected: 'HTTP 200 and content-type application/json',
    },
    {
      step: 2,
      title: 'Verify health route',
      command: `curl -i -H "Accept: application/json" "${baseUrl}/api/artymus?action=health"`,
      expected: 'JSON body with ok=true, service=ARTYMUS, health=green',
    },
    {
      step: 3,
      title: 'If HTML appears',
      command: 'Open vercel.json and remove any rewrite or route that sends /api/* to /index.html',
      expected: 'Only non-api paths should use the SPA fallback.',
    },
    {
      step: 4,
      title: 'Force clean deploy',
      command: 'Vercel redeploy with build cache disabled or run: vercel --prod --force',
      expected: 'Fresh route manifest generated by Vercel.',
    },
  ];
}

export default function handler(req: any, res: any) {
  if (req.method === 'OPTIONS') {
    res.status(204).end();
    return;
  }

  const action = typeof req.query?.action === 'string' ? req.query.action : 'status';
  const baseUrl = getBaseUrl(req);
  const checks = buildChecks(req);
  const failing = checks.filter((check) => !check.ok);

  const base = {
    ok: failing.length === 0,
    service: 'ARTYMUS-DEBUG',
    version: '1.0.0',
    stack: 'RT11 / ARTYMUS 3.0.1',
    mode: 'self-healing-debug',
    timestamp: new Date().toISOString(),
    baseUrl,
    endpoints: {
      status: '/api/debug',
      health: '/api/debug?action=health',
      diagnostics: '/api/debug?action=diagnostics',
      repairPlan: '/api/debug?action=repair-plan',
      artymus: '/api/artymus',
      artymusHealth: '/api/artymus?action=health',
    },
  };

  if (action === 'health') {
    json(res, 200, { ...base, health: failing.length === 0 ? 'green' : 'red', failingChecks: failing.length });
    return;
  }

  if (action === 'diagnostics') {
    json(res, 200, { ...base, checks });
    return;
  }

  if (action === 'repair-plan') {
    json(res, 200, { ...base, repairPlan: repairPlan(baseUrl) });
    return;
  }

  json(res, 200, {
    ...base,
    message: 'Self-healing debug service online. Use action=diagnostics or action=repair-plan.',
    checks,
  });
}
